services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: dreacode
      POSTGRES_PASSWORD:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: vinyl_share_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-net
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  networks:
    spring-net:
      driver: bridge

  volumes:
    postgres:
      driver: local